# Gradient 함수에서 input (Features) 정의

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
from mpl_toolkits.mplot3d import Axes3D

tf.random.set_seed(777)  # for reproducibility

print(tf.__version__)

2.5.0


## Data (features, labels)

In [2]:
x_train = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]

y_train = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

features = tf.cast(x_train, tf.float32)
labels = tf.cast(y_train, tf.float32)

## 가중치 설정

In [3]:
W = tf.Variable(tf.random.normal((3, 3)))
b = tf.Variable(tf.random.normal((3,)))

## Hypothesis

In [4]:
def model(features):
    hypothesis = tf.nn.softmax(tf.matmul(features, W) +b)
    return hypothesis

hypothesis = model(features)

## Cost 함수 정의

In [5]:
def loss_fn(hypothesis,labels):
    cost = tf.reduce_mean(-tf.reduce_sum(labels * tf.math.log(hypothesis), axis = 1))
    return cost

## Gradient 함수 Input

- input 변수는 features (x data)가 직접 되어야 함.
- for 문에서 features와 hypothesis 관계가 선언되더라도, hypothesis로 계산된 후 input이 되면 gard. 계산 안됨.

### 1. grad(features, labels)로 선언한 경우

In [6]:
def grad(features, labels):
    with tf.GradientTape() as tape:
        loss_value = loss_fn(model(features),labels)
    return tape.gradient(loss_value, [W,b])

grad(features, labels)                 # 정상 계산

[<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.24937233, -0.3747183 ,  0.6240906 ],
        [-1.6237042 , -1.7494293 ,  3.3731337 ],
        [-1.6243054 , -1.8747082 ,  3.4990134 ]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.24937233, -0.3747183 ,  0.6240906 ], dtype=float32)>]

### 2. grad(hypothesis, labels)로 선언한 경우
- grad 정의 과정에서 가중치가 hypothesis에 이미 계산되어 들어가면서 tape.gradient 가중치 지정이 의미 없음.

In [7]:
def grad(hypothesis, labels):
    with tf.GradientTape() as tape:
        loss_value = loss_fn(hypothesis,labels)
    return tape.gradient(loss_value, [W,b])

grad(hypothesis, labels)             # grad 계산값 없음.

[None, None]